-- Script para criar a tabela de cupons e adicionar colunas na tabela de pedidos

-- 0. Garantir que a função is_admin existe
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT auth.email() = 'ravilarutilidades@gmail.com';
$$;

-- 1. Criar tabela de cupons se não existir
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL DEFAULT 'percentage', -- 'percentage' ou 'fixed'
    value NUMERIC NOT NULL,
    min_purchase NUMERIC DEFAULT 0.00 NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    max_uses_per_client INT DEFAULT NULL, -- NULL ou 0 significa sem limites por cliente
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Garantir coluna em bancos existentes
ALTER TABLE public.coupons ADD COLUMN IF NOT EXISTS max_uses_per_client INT DEFAULT NULL;

-- 2. Habilitar RLS na tabela de cupons
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- 3. Criar políticas de RLS na tabela de cupons
DROP POLICY IF EXISTS "Permitir leitura pública de cupons" ON public.coupons;
DROP POLICY IF EXISTS "Permitir inserção admin de cupons" ON public.coupons;
DROP POLICY IF EXISTS "Permitir atualização admin de cupons" ON public.coupons;
DROP POLICY IF EXISTS "Permitir exclusão admin de cupons" ON public.coupons;

CREATE POLICY "Permitir leitura pública de cupons" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "Permitir inserção admin de cupons" ON public.coupons FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Permitir atualização admin de cupons" ON public.coupons FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Permitir exclusão admin de cupons" ON public.coupons FOR DELETE USING (public.is_admin());

-- 4. Adicionar colunas de cupons na tabela de pedidos se não existirem
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS coupon_code TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0.00 NOT NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC DEFAULT 0.00 NOT NULL;

-- Atualizar pedidos legados com o subtotal calculado retroativamente (Total Geral - Frete)
UPDATE public.orders SET subtotal = total_amount - shipping_fee WHERE subtotal = 0.00;

-- 5. Atualizar a função create_checkout_order para mapear cupom, desconto e subtotal, validando os limites de uso do cupom
CREATE OR REPLACE FUNCTION public.create_checkout_order(order_data JSONB, items_data JSONB)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_order_id BIGINT;
    item JSONB;
    requested_user_id UUID;
    existing_cust_id BIGINT;
    clean_phone TEXT;
    cust_email TEXT;
BEGIN
    IF jsonb_typeof(items_data) != 'array' OR jsonb_array_length(items_data) = 0 THEN
        RAISE EXCEPTION 'O pedido precisa ter pelo menos um item.';
    END IF;

    requested_user_id := NULLIF(order_data->>'user_id', '')::UUID;

    IF auth.uid() IS NULL THEN
        requested_user_id := NULL;
    ELSIF requested_user_id IS DISTINCT FROM auth.uid() THEN
        requested_user_id := auth.uid();
    END IF;

    -- Validar cupom no servidor (se aplicável)
    IF order_data->>'coupon_code' IS NOT NULL AND (order_data->>'coupon_code') != '' THEN
        DECLARE
            coupon_rec RECORD;
            existing_uses INT;
            clean_phone TEXT;
        BEGIN
            -- Buscar o cupom ativo
            SELECT * INTO coupon_rec FROM public.coupons 
            WHERE code = order_data->>'coupon_code' AND is_active = true;
            
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Cupom inválido ou inativo.';
            END IF;
            
            -- Verificar compra mínima
            IF (order_data->>'subtotal')::NUMERIC < coupon_rec.min_purchase THEN
                RAISE EXCEPTION 'O valor mínimo de produtos para este cupom não foi atingido.';
            END IF;
            
            -- Verificar limite de uso por cliente (Celular do formulário ou UUID se logado)
            IF coupon_rec.max_uses_per_client IS NOT NULL AND coupon_rec.max_uses_per_client > 0 THEN
                clean_phone := regexp_replace(order_data->>'client_phone', '\D', '', 'g');
                
                SELECT COUNT(*) INTO existing_uses FROM public.orders
                WHERE coupon_code = coupon_rec.code
                  AND (
                      regexp_replace(client_phone, '\D', '', 'g') = clean_phone
                      OR (requested_user_id IS NOT NULL AND user_id = requested_user_id)
                  );
                  
                IF existing_uses >= coupon_rec.max_uses_per_client THEN
                    RAISE EXCEPTION 'Este cupom já atingiu o limite de uso permitido para seu cadastro (% vez/vezes).', coupon_rec.max_uses_per_client;
                END IF;
            END IF;
        END;
    END IF;

    INSERT INTO public.orders (
        user_id,
        status,
        payment_method,
        payment_status,
        total_amount,
        shipping_fee,
        shipping_method,
        client_name,
        client_phone,
        client_email,
        cep,
        street,
        number,
        neighborhood,
        city,
        uf,
        complement,
        coupon_code,
        discount_amount,
        subtotal
    ) VALUES (
        requested_user_id,
        'Pendente',
        order_data->>'payment_method',
        'Pendente',
        (order_data->>'total_amount')::NUMERIC,
        COALESCE((order_data->>'shipping_fee')::NUMERIC, 0),
        COALESCE(order_data->>'shipping_method', 'Envio'),
        order_data->>'client_name',
        order_data->>'client_phone',
        NULLIF(order_data->>'client_email', ''),
        order_data->>'cep',
        order_data->>'street',
        order_data->>'number',
        order_data->>'neighborhood',
        order_data->>'city',
        order_data->>'uf',
        NULLIF(order_data->>'complement', ''),
        order_data->>'coupon_code',
        COALESCE((order_data->>'discount_amount')::NUMERIC, 0.00),
        COALESCE((order_data->>'subtotal')::NUMERIC, 0.00)
    )
    RETURNING id INTO new_order_id;

    FOR item IN SELECT * FROM jsonb_array_elements(items_data)
    LOOP
        INSERT INTO public.order_items (
            order_id,
            product_id,
            product_name,
            quantity,
            price
        ) VALUES (
            new_order_id,
            NULLIF(item->>'product_id', '')::BIGINT,
            item->>'product_name',
            (item->>'quantity')::INT,
            (item->>'price')::NUMERIC
        );
    END LOOP;

    -- Sincronizar/Upsert na tabela de clientes.
    -- A chave única da tabela customers é o TELEFONE (phone), não o e-mail.
    -- Bloco de exceção: falha no sync do cliente nunca cancela o pedido.
    BEGIN
        clean_phone := regexp_replace(order_data->>'client_phone', '\D', '', 'g');
        cust_email := NULLIF(order_data->>'client_email', '');

        IF clean_phone IS NOT NULL AND clean_phone != '' THEN
            INSERT INTO public.customers (
                phone,
                email,
                name,
                street,
                number,
                neighborhood,
                city
            ) VALUES (
                clean_phone,
                cust_email,
                order_data->>'client_name',
                order_data->>'street',
                order_data->>'number',
                order_data->>'neighborhood',
                (order_data->>'city') || ' - ' || (order_data->>'uf')
            )
            ON CONFLICT (phone) DO UPDATE SET
                email = COALESCE(EXCLUDED.email, public.customers.email),
                name = EXCLUDED.name,
                street = EXCLUDED.street,
                number = EXCLUDED.number,
                neighborhood = EXCLUDED.neighborhood,
                city = EXCLUDED.city;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'Falha ao sincronizar cliente no checkout: %', SQLERRM;
    END;

    RETURN new_order_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_checkout_order(JSONB, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_checkout_order(JSONB, JSONB) TO anon, authenticated;
