-- ==========================================================================
-- SCRIPT DE CRIAÇÃO DAS TABELAS DE VENDAS E CLIENTES - RAVILAR UTILIDADES
-- COPIE ESTE TEXTO E EXECUTE NO "SQL EDITOR" DO SEU PAINEL DO SUPABASE
-- ==========================================================================

-- 1. Criar a tabela de Pedidos (orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Vincula ao Auth do Supabase se logado
    status TEXT DEFAULT 'Pendente' NOT NULL, -- Pendente, Pago, Separando, Em Transporte, Entregue, Cancelado
    payment_method TEXT NOT NULL, -- Pix, Cartão de Crédito
    payment_status TEXT DEFAULT 'Pendente' NOT NULL, -- Pendente, Pago, Estornado, Recusado
    total_amount NUMERIC NOT NULL,
    shipping_fee NUMERIC DEFAULT 0.0 NOT NULL,
    shipping_method TEXT DEFAULT 'Envio' NOT NULL,
    client_name TEXT NOT NULL,
    client_phone TEXT NOT NULL,
    client_email TEXT,
    cep TEXT,
    street TEXT NOT NULL,
    number TEXT NOT NULL,
    neighborhood TEXT NOT NULL,
    city TEXT NOT NULL,
    uf TEXT NOT NULL,
    complement TEXT,
    tracking_code TEXT,
    coupon_code TEXT,
    discount_amount NUMERIC DEFAULT 0.00 NOT NULL,
    subtotal NUMERIC DEFAULT 0.00 NOT NULL
);

-- Garantir colunas em bancos existentes
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tracking_code TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS coupon_code TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0.00 NOT NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC DEFAULT 0.00 NOT NULL;

-- 2. Criar a tabela de Itens do Pedido (order_items)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC NOT NULL
);

-- 3. Criar a tabela de Favoritos (favorites)
CREATE TABLE IF NOT EXISTS public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    UNIQUE (user_id, product_id)
);

-- 4. Criar a tabela de Endereços do Cliente (client_addresses)
CREATE TABLE IF NOT EXISTS public.client_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL, -- Ex: "Casa", "Trabalho"
    cep TEXT,
    street TEXT NOT NULL,
    number TEXT NOT NULL,
    neighborhood TEXT NOT NULL,
    city TEXT NOT NULL,
    uf TEXT NOT NULL,
    complement TEXT,
    is_default BOOLEAN DEFAULT false NOT NULL
);

-- 5. Criar a tabela de Cartões do Cliente (client_cards)
CREATE TABLE IF NOT EXISTS public.client_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    cardholder_name TEXT NOT NULL,
    last_digits TEXT NOT NULL,
    brand TEXT NOT NULL,
    expiry TEXT NOT NULL
);

-- 6. Habilitar segurança de nível de linha (RLS) nas novas tabelas
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_cards ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT auth.email() = 'ravilarutilidades@gmail.com';
$$;

-- 7. Remover policies antigas dessas tabelas, independentemente do nome.
DO $$
DECLARE
    policy_row RECORD;
BEGIN
    FOR policy_row IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename IN ('orders', 'order_items', 'favorites', 'client_addresses', 'client_cards')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
    END LOOP;
END;
$$;

-- 8. Criar policies restritas.
CREATE POLICY "orders_select_owner_or_admin" ON public.orders
FOR SELECT USING (
    public.is_admin()
    OR user_id = auth.uid()
    OR (client_email IS NOT NULL AND client_email = auth.email())
);

CREATE POLICY "orders_insert_checkout" ON public.orders
FOR INSERT WITH CHECK (public.is_admin());

CREATE POLICY "orders_update_admin" ON public.orders
FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "orders_delete_admin" ON public.orders
FOR DELETE USING (public.is_admin());

CREATE POLICY "order_items_select_owner_or_admin" ON public.order_items
FOR SELECT USING (
    public.is_admin()
    OR EXISTS (
        SELECT 1 FROM public.orders
        WHERE orders.id = order_items.order_id
          AND (
              orders.user_id = auth.uid()
              OR (orders.client_email IS NOT NULL AND orders.client_email = auth.email())
          )
    )
);

CREATE POLICY "order_items_insert_checkout" ON public.order_items
FOR INSERT WITH CHECK (public.is_admin());

CREATE POLICY "order_items_update_admin" ON public.order_items
FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY "order_items_delete_admin" ON public.order_items
FOR DELETE USING (public.is_admin());

CREATE POLICY "favorites_owner_select" ON public.favorites
FOR SELECT USING (public.is_admin() OR user_id = auth.uid());

CREATE POLICY "favorites_owner_insert" ON public.favorites
FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "favorites_owner_update" ON public.favorites
FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "favorites_owner_delete" ON public.favorites
FOR DELETE USING (public.is_admin() OR user_id = auth.uid());

CREATE POLICY "client_addresses_owner_select" ON public.client_addresses
FOR SELECT USING (public.is_admin() OR user_id = auth.uid());

CREATE POLICY "client_addresses_owner_insert" ON public.client_addresses
FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "client_addresses_owner_update" ON public.client_addresses
FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "client_addresses_owner_delete" ON public.client_addresses
FOR DELETE USING (public.is_admin() OR user_id = auth.uid());

CREATE POLICY "client_cards_owner_select" ON public.client_cards
FOR SELECT USING (public.is_admin() OR user_id = auth.uid());

CREATE POLICY "client_cards_owner_insert" ON public.client_cards
FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "client_cards_owner_update" ON public.client_cards
FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "client_cards_owner_delete" ON public.client_cards
FOR DELETE USING (public.is_admin() OR user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.create_checkout_order(order_data JSONB, items_data JSONB)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_order_id BIGINT;
    item JSONB;
    requested_user_id UUID;
    existing_cust_id BIGINT;
    clean_phone TEXT;
    cust_email TEXT;
BEGIN
    IF jsonb_typeof(items_data) != 'array' OR jsonb_array_length(items_data) = 0 THEN
        RAISE EXCEPTION 'O pedido precisa ter pelo menos um item.';
    END IF;

    requested_user_id := NULLIF(order_data->>'user_id', '')::UUID;

    IF auth.uid() IS NULL THEN
        requested_user_id := NULL;
    ELSIF requested_user_id IS DISTINCT FROM auth.uid() THEN
        requested_user_id := auth.uid();
    END IF;

    -- Validar cupom no servidor (se aplicável)
    IF order_data->>'coupon_code' IS NOT NULL AND (order_data->>'coupon_code') != '' THEN
        DECLARE
            coupon_rec RECORD;
            existing_uses INT;
            coupon_phone TEXT;
        BEGIN
            SELECT * INTO coupon_rec FROM public.coupons
            WHERE code = order_data->>'coupon_code' AND is_active = true;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'Cupom inválido ou inativo.';
            END IF;

            IF (order_data->>'subtotal')::NUMERIC < coupon_rec.min_purchase THEN
                RAISE EXCEPTION 'O valor mínimo de produtos para este cupom não foi atingido.';
            END IF;

            IF coupon_rec.max_uses_per_client IS NOT NULL AND coupon_rec.max_uses_per_client > 0 THEN
                coupon_phone := regexp_replace(order_data->>'client_phone', '\D', '', 'g');

                SELECT COUNT(*) INTO existing_uses FROM public.orders
                WHERE coupon_code = coupon_rec.code
                  AND (
                      regexp_replace(client_phone, '\D', '', 'g') = coupon_phone
                      OR (requested_user_id IS NOT NULL AND user_id = requested_user_id)
                  );

                IF existing_uses >= coupon_rec.max_uses_per_client THEN
                    RAISE EXCEPTION 'Este cupom já atingiu o limite de uso permitido para seu cadastro (% vez/vezes).', coupon_rec.max_uses_per_client;
                END IF;
            END IF;
        END;
    END IF;

    INSERT INTO public.orders (
        user_id,
        status,
        payment_method,
        payment_status,
        total_amount,
        shipping_fee,
        shipping_method,
        client_name,
        client_phone,
        client_email,
        cep,
        street,
        number,
        neighborhood,
        city,
        uf,
        complement,
        coupon_code,
        discount_amount,
        subtotal
    ) VALUES (
        requested_user_id,
        'Pendente',
        order_data->>'payment_method',
        'Pendente',
        (order_data->>'total_amount')::NUMERIC,
        COALESCE((order_data->>'shipping_fee')::NUMERIC, 0),
        COALESCE(order_data->>'shipping_method', 'Envio'),
        order_data->>'client_name',
        order_data->>'client_phone',
        NULLIF(order_data->>'client_email', ''),
        order_data->>'cep',
        order_data->>'street',
        order_data->>'number',
        order_data->>'neighborhood',
        order_data->>'city',
        order_data->>'uf',
        NULLIF(order_data->>'complement', ''),
        NULLIF(order_data->>'coupon_code', ''),
        COALESCE((order_data->>'discount_amount')::NUMERIC, 0.00),
        COALESCE((order_data->>'subtotal')::NUMERIC, 0.00)
    )
    RETURNING id INTO new_order_id;

    FOR item IN SELECT * FROM jsonb_array_elements(items_data)
    LOOP
        INSERT INTO public.order_items (
            order_id,
            product_id,
            product_name,
            quantity,
            price
        ) VALUES (
            new_order_id,
            NULLIF(item->>'product_id', '')::BIGINT,
            item->>'product_name',
            (item->>'quantity')::INT,
            (item->>'price')::NUMERIC
        );
    END LOOP;

    -- Sincronizar/Upsert na tabela de clientes.
    -- A chave única da tabela customers é o TELEFONE (phone), não o e-mail.
    -- Envolvido em bloco de exceção para que uma falha no sync do cliente
    -- nunca cancele a criação do pedido.
    BEGIN
        clean_phone := regexp_replace(order_data->>'client_phone', '\D', '', 'g');
        cust_email := NULLIF(order_data->>'client_email', '');

        IF clean_phone IS NOT NULL AND clean_phone != '' THEN
            INSERT INTO public.customers (
                phone,
                email,
                name,
                street,
                number,
                neighborhood,
                city
            ) VALUES (
                clean_phone,
                cust_email,
                order_data->>'client_name',
                order_data->>'street',
                order_data->>'number',
                order_data->>'neighborhood',
                (order_data->>'city') || ' - ' || (order_data->>'uf')
            )
            ON CONFLICT (phone) DO UPDATE SET
                email = COALESCE(EXCLUDED.email, public.customers.email),
                name = EXCLUDED.name,
                street = EXCLUDED.street,
                number = EXCLUDED.number,
                neighborhood = EXCLUDED.neighborhood,
                city = EXCLUDED.city;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'Falha ao sincronizar cliente no checkout: %', SQLERRM;
    END;

    RETURN new_order_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_checkout_order(JSONB, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_checkout_order(JSONB, JSONB) TO anon, authenticated;

-- 9. Criar tabela de configurações gerais da loja (store_settings)
CREATE TABLE IF NOT EXISTS public.store_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
DO $$
DECLARE
    policy_row RECORD;
BEGIN
    FOR policy_row IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'store_settings'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
    END LOOP;
END;
$$;
CREATE POLICY "store_settings_public_select" ON public.store_settings
FOR SELECT USING (key != 'melhor_envio_token' OR public.is_admin());
CREATE POLICY "store_settings_admin_insert" ON public.store_settings
FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "store_settings_admin_update" ON public.store_settings
FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "store_settings_admin_delete" ON public.store_settings
FOR DELETE USING (public.is_admin());

-- Inserir configurações de frete padrão e Melhor Envio
INSERT INTO public.store_settings (key, value) VALUES 
('default_shipping_fee', '15.00'),
('free_shipping_min_amount', '150.00'),
('origin_cep', '17996371'),
('melhor_envio_token', ''),
('melhor_envio_sandbox', 'true')
ON CONFLICT (key) DO NOTHING;

-- 10. Criar tabela de regras de frete por CEP (shipping_rules)
CREATE TABLE IF NOT EXISTS public.shipping_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cep_prefix TEXT NOT NULL UNIQUE,
    price NUMERIC NOT NULL
);
ALTER TABLE public.shipping_rules ENABLE ROW LEVEL SECURITY;
DO $$
DECLARE
    policy_row RECORD;
BEGIN
    FOR policy_row IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'shipping_rules'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
    END LOOP;
END;
$$;
CREATE POLICY "shipping_rules_public_select" ON public.shipping_rules FOR SELECT USING (true);
CREATE POLICY "shipping_rules_admin_insert" ON public.shipping_rules FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "shipping_rules_admin_update" ON public.shipping_rules FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "shipping_rules_admin_delete" ON public.shipping_rules FOR DELETE USING (public.is_admin());

-- 11. Habilitar extensão HTTP (se não existir) e criar função RPC de cálculo de frete
CREATE EXTENSION IF NOT EXISTS http;

CREATE OR REPLACE FUNCTION public.calculate_shipping(
    from_cep TEXT,
    to_cep TEXT,
    items_count INT,
    total_value NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    me_token TEXT;
    me_sandbox TEXT;
    api_url TEXT := 'https://www.melhorenvio.com.br/api/v2/me/shipment/calculate';
    req_body TEXT;
    response_status INT;
    response_content TEXT;
BEGIN
    -- Obter o token do Melhor Envio das configurações da loja
    SELECT value INTO me_token FROM public.store_settings WHERE key = 'melhor_envio_token';
    SELECT value INTO me_sandbox FROM public.store_settings WHERE key = 'melhor_envio_sandbox';
    
    IF me_token IS NULL OR me_token = '' THEN
        RETURN jsonb_build_object('error', 'Token do Melhor Envio não configurado.');
    END IF;

    -- Alternar entre ambiente de produção e testes sandbox
    IF me_sandbox = 'true' THEN
        api_url := 'https://sandbox.melhorenvio.com.br/api/v2/me/shipment/calculate';
    END IF;

    -- Montar o corpo da requisição com tamanho padrão estimado com base na quantidade de produtos
    req_body := json_build_object(
        'from', json_build_object('postal_code', replace(from_cep, '-', '')),
        'to', json_build_object('postal_code', replace(to_cep, '-', '')),
        'products', json_build_array(
            json_build_object(
                'id', 'pacote_estimado',
                'width', 15,
                'height', 15,
                'length', 20,
                'weight', 0.4 * items_count,
                'insurance_value', total_value,
                'quantity', 1
            )
        )
    )::text;

    -- Executar chamada HTTP POST
    SELECT 
        status, 
        content 
    INTO 
        response_status, 
        response_content
    FROM http((
        'POST',
        api_url,
        ARRAY[
            http_header('Authorization', 'Bearer ' || me_token),
            http_header('Content-Type', 'application/json'),
            http_header('Accept', 'application/json')
        ],
        'application/json',
        req_body
    )::http_request);

    -- Verificar se a chamada retornou sucesso
    IF response_status >= 200 AND response_status < 300 THEN
        RETURN response_content::jsonb;
    ELSE
        RETURN jsonb_build_object(
            'error', 'Erro ao consultar a API do Melhor Envio',
            'status', response_status,
            'response', response_content::jsonb
        );
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('error', SQLERRM);
END;
$$;
