-- ==========================================================================
-- SCRIPT DE INICIALIZAÇÃO DO BANCO DE DADOS - RAVILAR UTILIDADES
-- COPIE ESTE TEXTO E EXECUTE NO "SQL EDITOR" DO SEU PAINEL DO SUPABASE
-- ==========================================================================

-- 1. Criar a tabela de categorias caso ela não exista
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    image TEXT NOT NULL
);

-- 2. Criar a tabela de produtos caso ela não exista
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- Corresponde ao slug da categoria
    price NUMERIC NOT NULL,
    image TEXT NOT NULL, -- Guardará vetor de URLs em formato JSON ex: ["url1", "url2"]
    description TEXT NOT NULL,
    badge TEXT,
    rating NUMERIC DEFAULT 5.0,
    reviews BIGINT DEFAULT 0
);

-- 3. Criar a tabela de banners/slides caso ela não exista
CREATE TABLE IF NOT EXISTS public.banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    image TEXT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT NOT NULL
);

-- 4. Criar a tabela de avaliações/depoimentos caso ela não exista
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    name TEXT NOT NULL,
    quote TEXT NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    rating INT DEFAULT 5
);

-- 5. Habilitar segurança de nível de linha (RLS) nas quatro tabelas
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 6. Remover políticas antigas se já existirem
DROP POLICY IF EXISTS "Permitir leitura pública" ON public.categories;
DROP POLICY IF EXISTS "Permitir inserção pública" ON public.categories;
DROP POLICY IF EXISTS "Permitir atualização pública" ON public.categories;
DROP POLICY IF EXISTS "Permitir exclusão pública" ON public.categories;

DROP POLICY IF EXISTS "Permitir leitura pública" ON public.products;
DROP POLICY IF EXISTS "Permitir inserção pública" ON public.products;
DROP POLICY IF EXISTS "Permitir atualização pública" ON public.products;
DROP POLICY IF EXISTS "Permitir exclusão pública" ON public.products;

DROP POLICY IF EXISTS "Permitir leitura pública" ON public.banners;
DROP POLICY IF EXISTS "Permitir inserção pública" ON public.banners;
DROP POLICY IF EXISTS "Permitir atualização pública" ON public.banners;
DROP POLICY IF EXISTS "Permitir exclusão pública" ON public.banners;

DROP POLICY IF EXISTS "Permitir leitura pública" ON public.reviews;
DROP POLICY IF EXISTS "Permitir inserção pública" ON public.reviews;
DROP POLICY IF EXISTS "Permitir atualização pública" ON public.reviews;
DROP POLICY IF EXISTS "Permitir exclusão pública" ON public.reviews;

-- 7. Criar políticas para tabela de categorias
CREATE POLICY "Permitir leitura pública" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Permitir inserção pública" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualização pública" ON public.categories FOR UPDATE USING (true);
CREATE POLICY "Permitir exclusão pública" ON public.categories FOR DELETE USING (true);

-- 8. Criar políticas para tabela de produtos
CREATE POLICY "Permitir leitura pública" ON public.products FOR SELECT USING (true);
CREATE POLICY "Permitir inserção pública" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualização pública" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Permitir exclusão pública" ON public.products FOR DELETE USING (true);

-- 9. Criar políticas para tabela de banners
CREATE POLICY "Permitir leitura pública" ON public.banners FOR SELECT USING (true);
CREATE POLICY "Permitir inserção pública" ON public.banners FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualização pública" ON public.banners FOR UPDATE USING (true);
CREATE POLICY "Permitir exclusão pública" ON public.banners FOR DELETE USING (true);

-- 10. Criar políticas para tabela de avaliações
CREATE POLICY "Permitir leitura pública" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Permitir inserção pública" ON public.reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualização pública" ON public.reviews FOR UPDATE USING (true);
CREATE POLICY "Permitir exclusão pública" ON public.reviews FOR DELETE USING (true);

-- 11. CONFIGURAR SUPABASE STORAGE PARA UPLOAD DE IMAGENS E VÍDEOS
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-media', 'product-media', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Permitir leitura pública de mídia" ON storage.objects;
DROP POLICY IF EXISTS "Permitir upload de mídia" ON storage.objects;
DROP POLICY IF EXISTS "Permitir atualização de mídia" ON storage.objects;
DROP POLICY IF EXISTS "Permitir exclusão de mídia" ON storage.objects;

CREATE POLICY "Permitir leitura pública de mídia" ON storage.objects FOR SELECT USING (bucket_id = 'product-media');
CREATE POLICY "Permitir upload de mídia" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'product-media');
CREATE POLICY "Permitir atualização de mídia" ON storage.objects FOR UPDATE USING (bucket_id = 'product-media');
CREATE POLICY "Permitir exclusão de mídia" ON storage.objects FOR DELETE USING (bucket_id = 'product-media');

-- 12. Limpar tabelas antes de carregar dados iniciais
TRUNCATE TABLE public.categories CASCADE;
TRUNCATE TABLE public.products CASCADE;
TRUNCATE TABLE public.banners CASCADE;
TRUNCATE TABLE public.reviews CASCADE;

-- 13. Inserir as 4 categorias padrão iniciais
INSERT INTO public.categories (name, slug, image) VALUES
('Cozinha', 'cozinha', 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&q=80&w=400'),
('Organização', 'organizacao', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&q=80&w=400'),
('Mesa Posta', 'mesa-posta', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=400'),
('Decoração', 'decoracao', 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=400');

-- 14. Inserir os 3 banners de cabeçalho iniciais (crossfade hero sliders)
INSERT INTO public.banners (image, title, subtitle) VALUES
('https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800', 'Design Premium', 'Qualidade selecionada'),
('https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&q=80&w=800', 'Praticidade', 'Organizadores inteligentes'),
('https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800', 'Mesa Posta', 'Requinte nas refeições');

-- 15. Inserir os 30 produtos reais da Nota Fiscal
INSERT INTO public.products (name, category, price, image, description, badge, rating, reviews) VALUES
('Forma Para Moldar Hamburguer Recheado 3 em 1', 'cozinha', 11.99, '["https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600"]', 'Prepare hambúrgueres perfeitos e recheados em casa com esta forma prática 3 em 1. Feita com material resistente e fácil de limpar, molda hambúrgueres de diferentes tamanhos com acabamento profissional.', 'Destaque', 4.8, 12),
('Forma Para Air Fryer De Silicone Antiaderente - Sem Sujeira', 'cozinha', 4.99, '["https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?auto=format&fit=crop&q=80&w=600"]', 'Chega de gordura encrostada na sua fritadeira! Esta forma de silicone flexível e antiaderente suporta altas temperaturas, facilita o manuseio dos alimentos e é super fácil de lavar. Reutilizável e ecológica.', 'Mais Vendido', 4.9, 87),
('Balança Cozinha Digital 10kg Alta Precisão Dieta e Nutrição', 'cozinha', 13.99, '["https://images.unsplash.com/photo-1603706125194-6d43e5c94297?auto=format&fit=crop&q=80&w=600"]', 'Pese seus ingredientes com precisão cirúrgica de até 10kg. Ideal para receitas de panificação, controle de porções de dietas ou medições de precisão. Display digital de fácil leitura e função Tara.', 'Mais Vendido', 4.8, 45),
('Pratos de Sobremesa Plástico Coloridos com Base Organizadora Kit 10', 'mesa-posta', 9.99, '["https://images.unsplash.com/photo-1536304997881-a372c179924b?auto=format&fit=crop&q=80&w=600"]', 'Conjunto alegre com 10 pratos de sobremesa coloridos feitos em plástico resistente de alta qualidade. Acompanha base organizadora vertical para economizar espaço no armário e manter tudo no lugar.', 'Novidade', 4.7, 16),
('Suporte Organizador para 30 Ovos com Rolamento Automático', 'organizacao', 11.99, '["https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&q=80&w=600"]', 'Organizador de ovos inteligente de fluxo rolante. Comporta até 30 ovos que deslizam suavemente para a frente à medida que você retira o anterior. Design vertical compacto perfeito para geladeiras ou despensas.', 'Mais Vendido', 4.9, 38),
('Kit com 4 Potes Herméticos 150ml com Tampa e Travas para Lancheira', 'organizacao', 10.99, '["https://images.unsplash.com/photo-1595348020949-87cdfcd44174?auto=format&fit=crop&q=80&w=600"]', 'Perfeitos para lanches rápidos, molhos ou papinhas. Este conjunto vem com 4 potes herméticos de 150ml equipados com travas nas laterais e vedação de silicone que garante zero vazamento.', 'Novidade', 4.6, 9),
('Defletor de Ar Condicionado Split Direcionador de Vento Universal Ajustável', 'organizacao', 17.99, '["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=600"]', 'Evite o vento gelado direto no rosto ou corpo. Este direcionador de vento universal e ajustável é fácil de instalar em qualquer ar condicionado split sem necessidade de furos, melhorando a climatização do ambiente.', '', 4.5, 14),
('Kit Medidor Culinário Colher Copo Em Aço Inox - 08 Peças', 'cozinha', 15.99, '["https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&q=80&w=600"]', 'Kit completo com 4 copos medidores e 4 colheres medidoras em aço inoxidável premium de alta durabilidade. As marcações gravadas garantem medidas perfeitas para que suas receitas saiam idênticas às profissionais.', 'Destaque', 4.8, 22),
('Cortador Multi Fatiador Nicer Alimentos e Frutas Cinza 13 em 1', 'cozinha', 32.99, '["https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&q=80&w=600"]', 'Economize tempo na cozinha! O fatiador e cortador multiuso 13 em 1 fatia, rala e corta legumes, verduras e frutas em diferentes formatos com precisão e segurança. Acompanha recipiente organizador de resíduos.', 'Destaque', 4.7, 33),
('Conjunto de Tigelas Potes de Inox com Tampa - 5 peças', 'organizacao', 16.99, '["https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=600"]', 'Conjunto com 5 tigelas de aço inoxidável resistentes, ideais para misturar ingredientes, servir saladas ou guardar alimentos no refrigerador. Acompanha tampas flexíveis para vedação rápida e segura.', 'Oferta', 4.6, 21),
('Abajur Luminária Touch Sem Fio Cristal RGB 16 Cores', 'decoracao', 19.99, '["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600"]', 'Adicione requinte e modernidade a qualquer espaço. Esta luminária em formato de cristal reflete belos efeitos visuais geométricos e oferece 16 cores selecionáveis por toque ou controle remoto. Bateria recarregável sem fio.', 'Mais Vendido', 4.8, 56),
('Luva Microfibra Macia Para Limpeza e Lavagem Automotiva', 'organizacao', 5.99, '["https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=600"]', 'Ideal para limpar poeira de móveis ou lavar o carro sem riscar a lataria e vidros. Feita de microfibra de alta absorção que retém as partículas de sujeira com extrema suavidade.', '', 4.6, 12),
('Utensílios De Cozinha Silicone com Fue - Kit c/ 5', 'cozinha', 14.99, '["https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&q=80&w=600"]', 'Kit essencial com 5 utensílios de silicone maciço que suportam altas temperaturas. Não arranham panelas antiaderentes e oferecem empunhadura confortável. Acompanha batedor de ovos (fue).', 'Oferta', 4.7, 19),
('Descascador de Legumes com Lâmina Afiada em Aço Inox', 'cozinha', 4.99, '["https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&q=80&w=600"]', 'Descasque batatas, cenouras e abobrinhas in segundos com esta lâmina afiada em aço inox de movimento oscilante. Cabo ergonômico e encaixe lateral para remoção de imperfeições.', '', 4.5, 31),
('Kit C/12 Utensílios De Cozinha Silicone Cabo Madeira', 'cozinha', 28.99, '["https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&q=80&w=600"]', 'Jogo de utensílios gourmet de 12 peças em silicone nobre e cabo de madeira tratada. Resistentes ao calor e de excelente empunhadura, acompanha balde organizador que dá um charme rústico à sua bancada.', 'Destaque', 4.9, 14),
('Kit de Tampas de Silicone Universal - 6 peças', 'cozinha', 7.99, '["https://images.unsplash.com/photo-1595348020949-87cdfcd44174?auto=format&fit=crop&q=80&w=600"]', 'Tampas elásticas de silicone que se adaptam a diferentes tamanhos de potes, tigelas, copos e até frutas cortadas. Vedação hermética perfeita que conserva o frescor dos alimentos.', 'Mais Vendido', 4.7, 52),
('Conjunto Colher Medidores Culinários 6 Medidas Cook Easy', 'cozinha', 6.99, '["https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&q=80&w=600"]', 'Faça receitas precisas com facilidade. Kit com 6 colheres medidoras empilháveis de plástico rígido. Excelente para confeitaria e dosagens culinárias rápidas.', '', 4.5, 8),
('Adesivos Repelentes de Mosquitos Kit com 36', 'organizacao', 3.50, '["https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600"]', 'Mantenha mosquitos e insetos longe de crianças e bebês de forma natural e sem odor. Adesivos autocolantes com óleos essenciais naturais que podem ser colados em roupas, bonés ou carrinhos.', 'Novidade', 4.6, 17),
('Mini Mixer Misturador Batedor Ovos e Bebidas Elétrico Recarregável', 'cozinha', 14.99, '["https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600"]', 'Prepare espumas cremosas para café, bata ovos ou misture wheys em segundos. Este batedor elétrico recarregável de alta rotação possui carregamento USB e pontas removíveis intercambiáveis.', 'Destaque', 4.8, 29),
('Porta Sabonete Líquido Minimalista 300ml - Branco', 'decoracao', 7.99, '["https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&q=80&w=600"]', 'Porta sabonete líquido ou loção com design minimalista escandinavo. Com capacidade para 300ml, seu acabamento em branco fosco traz leveza e sofisticação para banheiros ou lavabos.', '', 4.6, 5),
('Processador Alimentos Manual 3 Lâminas Triturador', 'cozinha', 12.99, '["https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&q=80&w=600"]', 'Triture cebola, alho, temperos ou castanhas rapidamente puxando a corda retrátil. Equipado com 3 lâminas afiadas de aço inox and base antiderrapante para total estabilidade no manuseio.', 'Mais Vendido', 4.9, 115),
('Luminária De Mesa Touch Capivara', 'decoracao', 26.99, '["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600"]', 'Luminária noturna fofa em formato de capivara, feita em silicone macio ao toque. Possui controle de brilho por toque físico, luz quente aconchegante and bateria interna recarregável.', 'Novidade', 4.9, 44),
('Pistola Divertida De Bolhas Com 10 Saídas Bubble Gun', 'decoracao', 18.99, '["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600"]', 'Gere milhares de bolhas de sabão por minuto com a incrível pistola de 10 saídas. Diversão garantida para festas de aniversário infantis ou brincadeiras ao ar livre no quintal.', '', 4.4, 23),
('Conjunto Chave de Fenda Magnética 24 em 1 para Eletrônicos e Celulares', 'organizacao', 7.99, '["https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600"]', 'Estojo compacto de alumínio com 24 ponteiras de precisão magnéticas de alta resistência (aço S2). Ideal para abrir celulares, computadores, relógios, óculos ou pequenos eletrodomésticos.', 'Mais Vendido', 4.8, 67),
('Saca Rolha Tipo Borboleta Multiuso', 'cozinha', 12.99, '["https://images.unsplash.com/photo-1602881917760-7379db593981?auto=format&fit=crop&q=80&w=600"]', 'Abra garrafas de vinho sem esforço and com total elegância. Este saca-rolhas clássico tipo borboleta possui engrenagens robustas and abridor de garrafas integrado no topo.', '', 4.6, 12),
('Adesivo Régua de Crescimento Infantil para Parede', 'decoracao', 5.99, '["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=600"]', 'Acompanhe o crescimento dos pequenos de forma lúdica. Adesivo autocolante com régua de altura and ilustrações decorativas. Fácil aplicação and remoção sem danificar a pintura da parede.', 'Novidade', 4.5, 9),
('Galheteiro de Vidro 500ml com Bico Dosador para Azeite Óleo e Vinagre', 'mesa-posta', 10.99, '["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=600"]', 'Garrafa de vidro borossilicato de 500ml com tampa inteligente de bico dosador corta-gotas de inox. Ideal para conservar and servir azeites, vinagres ou molhos à mesa com total higiene.', 'Novidade', 4.7, 11),
('Luminária Lâmpada Infantil Silicone Pato Recarregável', 'decoracao', 24.99, '["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600"]', 'Luminária decorativa em silicone macio BPA-free com design de patinho. Toque para acender ou mudar a intensidade da luz. Possui timer de desligamento automático de 30 minutos.', 'Destaque', 4.8, 19),
('Manta Cobertor Infantil Mágico Brilha No Escuro', 'decoracao', 34.99, '["https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&q=80&w=600"]', 'Manta super macia and aconchegante com estampas divertidas de estrelas que carregam sob a luz and brilham no escuro. Proporcione noites mais tranquilas and divertidas para as crianças.', 'Destaque', 4.9, 15),
('Dispenser Detergente 2 em 1 Esponja Limpeza Louça Dosador', 'cozinha', 8.99, '["https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=600"]', 'Otimize a pia da cozinha! Este dispenser dosador comporta detergente líquido no reservatório inferior and organiza a esponja na parte superior. Pressione para dosar o sabão direto na esponja sem desperdício.', 'Mais Vendido', 4.7, 63);

-- 16. Inserir avaliações iniciais padrão vinculadas aos produtos da loja
INSERT INTO public.reviews (name, quote, product_id, rating) VALUES
('Mariana Sousa', 'Os potes herméticos são maravilhosos! A vedação é perfeita e deixou a minha despensa super organizada e linda. O atendimento foi nota 10!', (SELECT id FROM public.products WHERE name = 'Kit com 4 Potes Herméticos 150ml com Tampa e Travas para Lancheira' LIMIT 1), 5),
('Ricardo Ferreira', 'Comprei o kit de utensílios de silicone e me surpreendi com a qualidade. Eles não riscam as panelas e o cabo em bambu dá um charme especial na cozinha.', (SELECT id FROM public.products WHERE name = 'Kit C/12 Utensílios De Cozinha Silicone Cabo Madeira' LIMIT 1), 5),
('Ana Oliveira', 'Amei o galheteiro de vidro borossilicato! Super higiênico, não escorre azeite na garrafa e fica lindo na mesa do almoço.', (SELECT id FROM public.products WHERE name = 'Galheteiro de Vidro 500ml com Bico Dosador para Azeite Óleo e Vinagre' LIMIT 1), 5);
